[package]
name = "plot"
entry = "src/app.zi"
module_roots = ["src", "tests"]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"
module_aliases = { Kryon = "kryon", PlotWidget = "plot_widget" }

[exports]
plot = "src/module.zi"
Plot = "src/module.zi"

[tool.kryon]
default_profile = "cairo"

[tool.kryon.profiles.cairo]
backend = "desktop"
